apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: perf-test
spec:
  selector:
    app: locust
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: NodePort # o LoadBalancer según tu entorno
