apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: perf-test
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter.perf-test.svc.cluster.local:9187']