apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: perf-test
  labels:
    app: postgres-exporter
spec:
  ports:
    - name: http
      port: 9187
      targetPort: 9187
  selector:
    app: postgres-exporter
